export const NOTIFICATION_TYPES = {
  PROJECT_STATUS: 'project_status',
  INVOICE_SENT: 'invoice_sent',
  INVOICE_PAID: 'invoice_paid',
  CONTRACT_SENT: 'contract_sent',
  CONTRACT_SIGNED: 'contract_signed',
  CONTRACT_PENDING_REVIEW: 'contract_pending_review',
  CONTRACT_UPLOAD_REJECTED: 'contract_upload_rejected',
  DELIVERABLE_UPLOADED: 'deliverable_uploaded',
  DELIVERABLE_REVIEWED: 'deliverable_reviewed',
  FILMING_REQUEST_STATUS: 'filming_request_status',
  NEW_MESSAGE: 'new_message',
  BOOKING_SUBMITTED: 'booking_submitted',
  TASK_ASSIGNED: 'task_assigned',
  TASK_UPDATED: 'task_updated',
  // Google Calendar Sync
  GOOGLE_NEW_EVENT: 'google_new_event',
  GOOGLE_EVENT_CHANGED: 'google_event_changed',
  GOOGLE_EVENT_DELETED: 'google_event_deleted',
  // Automated Email Notifications
  EMAIL_FILMING_REMINDER: 'email_filming_reminder',
  EMAIL_INVOICE_SENT: 'email_invoice_sent',
  EMAIL_PROJECT_DELIVERED: 'email_project_delivered',
  EMAIL_HOLIDAY_GREETING: 'email_holiday_greeting',
} as const;

// Map notification types to preference keys for checking user preferences
export const TYPE_TO_PREFERENCE: Record<string, string> = {
  [NOTIFICATION_TYPES.PROJECT_STATUS]: 'project_updates',
  [NOTIFICATION_TYPES.INVOICE_SENT]: 'invoice_reminders',
  [NOTIFICATION_TYPES.INVOICE_PAID]: 'invoice_reminders',
  [NOTIFICATION_TYPES.CONTRACT_SENT]: 'project_updates',
  [NOTIFICATION_TYPES.CONTRACT_SIGNED]: 'project_updates',
  [NOTIFICATION_TYPES.CONTRACT_PENDING_REVIEW]: 'project_updates',
  [NOTIFICATION_TYPES.CONTRACT_UPLOAD_REJECTED]: 'project_updates',
  [NOTIFICATION_TYPES.DELIVERABLE_UPLOADED]: 'new_deliverables',
  [NOTIFICATION_TYPES.DELIVERABLE_REVIEWED]: 'new_deliverables',
  [NOTIFICATION_TYPES.FILMING_REQUEST_STATUS]: 'filming_reminders',
  [NOTIFICATION_TYPES.NEW_MESSAGE]: 'messages',
  [NOTIFICATION_TYPES.BOOKING_SUBMITTED]: 'project_updates',
  [NOTIFICATION_TYPES.TASK_ASSIGNED]: 'project_updates',
  [NOTIFICATION_TYPES.TASK_UPDATED]: 'project_updates',
  [NOTIFICATION_TYPES.GOOGLE_NEW_EVENT]: 'project_updates',
  [NOTIFICATION_TYPES.GOOGLE_EVENT_CHANGED]: 'project_updates',
  [NOTIFICATION_TYPES.GOOGLE_EVENT_DELETED]: 'project_updates',
  [NOTIFICATION_TYPES.EMAIL_FILMING_REMINDER]: 'filming_reminders',
  [NOTIFICATION_TYPES.EMAIL_INVOICE_SENT]: 'invoice_reminders',
  [NOTIFICATION_TYPES.EMAIL_PROJECT_DELIVERED]: 'new_deliverables',
  [NOTIFICATION_TYPES.EMAIL_HOLIDAY_GREETING]: 'project_updates',
};
